import type { Metadata } from "next";
import "./globals.css";

import Layout from "@/components/Layout";
import { ShoppinCartContextProvider } from "@/context/ShoppingCartContext";

export const metadata: Metadata = {
  title: "Shopping Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ShoppinCartContextProvider>
          <Layout>{children}</Layout>
        </ShoppinCartContextProvider>
      </body>
    </html>
  );
}
